# Generated by Django 5.2.4 on 2025-07-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="название услуги"),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="описание услуги"),
                ),
                ("price", models.IntegerField(verbose_name="цена")),
                (
                    "unit_of_measurement",
                    models.CharField(
                        choices=[
                            ("hour", "час"),
                            ("square meter", "м2"),
                            ("cubic meter", "м3"),
                            ("ton", "т"),
                            ("empty", " "),
                        ],
                        default="hour",
                        help_text="Выберите единицу измерения",
                        max_length=16,
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["name", "price"],
            },
        ),
    ]
