# Generated by Django 5.2.4 on 2025-08-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal_services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Legislation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                (
                    "description",
                    models.CharField(
                        max_length=500, verbose_name="описание законодательства"
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="photos/")),
            ],
            options={
                "verbose_name": "закон",
                "verbose_name_plural": "законы",
                "ordering": ["title", "created_at"],
            },
        ),
    ]
