# Generated by Django 5.2.4 on 2025-08-19 12:24

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legal_services", "0002_legislation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legislation",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(upload_to="photos/"),
        ),
    ]
